global:
  scrape_interval: 15s
# TODO: update it when use docker
scrape_configs:
  - job_name: "api-gateway"
    static_configs:
      - targets: ["192.168.202.110:9095"]

  - job_name: "dispatcher"
    static_configs:
      - targets: ["192.168.202.110:9094"]

  - job_name: "worker-email"
    static_configs:
      - targets: ["192.168.202.110:9091"]

  - job_name: "worker-webhook"
    static_configs:
      - targets: ["192.168.202.110:9092"]

  - job_name: "scheduler"
    static_configs:
      - targets: ["192.168.202.110:9093"]
