apiVersion: v1
kind: Secret
metadata:
  name: taskflow-secret
  namespace: default
type: Opaque
# Values are base64-encoded. To encode: echo -n "value" | base64
# jwt-secret:    echo -n "changeme"                     | base64  â†’ Y2hhbmdlbWU=
# postgres-dsn:  echo -n "postgres://..." | base64
data:
  jwt-secret: Y2hhbmdlbWU=
  postgres-dsn: cG9zdGdyZXM6Ly90YXNrZmxvdzp0YXNrZmxvd0Bwb3N0Z3Jlczo1NDMyL3Rhc2tmbG93P3NzbG1vZGU9ZGlzYWJsZQ==
